### PR TITLE
fix(deps) : update arborist package to get rid of deprecated warning

### LINKED ISSUE #3550: Installing lerna shows two deprecated warnings for used module functionality
When installing lerna via npm install two warning are being showed about the usage of deprecated functionalities of used modules. This is present in both older version (5.5.2) and on the most recent version (6.5.1)

npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

## Expected Behavior

I would prefer the replacement of the deprecated code to avoid potential future issues as soon as possible.

## Steps to Reproduce

Create an empty folder and create a package.json file in that folder with the following content.

```
{
  "name": "test-app",
  "devDependencies": {
    "lerna": "6.5.1"
  }
}
```

Run `npm install` and notice the warning message regarding deprecated functionality.

### Failure Logs / Configuration

```
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
```

### PR DESCRIPTION
**Pull request by amorscher**
Partially fixes #3550

## Description
Updates to the actual version of npmcli/arborist which causes following deprecation warning to disappear. 

`npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs`

## Motivation and Context
Partially fixes #3550 

## How Has This Been Tested?
Existing unit, integration and e2e tests. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (change that has absolutely no effect on users)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by amorscher** [comment]
@JamesHenry @fahslaj eslint is complaining. Can I add the failure to the esignore patterns

**Comment by JamesHenry** [comment]
@amorscher The lint error is occurring within a file nested within `lerna/node_modules`, which should not exist at all. So that has been introduced by this change and needs to be resolved before proceeding

**Review by JamesHenry — CHANGES_REQUESTED** [review]
See comment

**Comment by amorscher** [comment]
@JamesHenry so I also updated dependant versions of arborist packe so that all modules are hoisted.

**Review by JamesHenry — APPROVED** [review]
Thank you @amorscher!

**Pull request merged**
