### PR TITLE
2.0.0-beta.33 changelog [skip ci]

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by gigabo** [comment]
@hzoo Want me to regenerate this with `lerna-changelog` to get links in?

**Comment by hzoo** [comment]
Sure feel free to modify, we should use lerna-changelog yea 😄

**Comment by gigabo** [comment]
Updated and opened a PR to add the config: https://github.com/lerna/lerna/pull/531

**Comment by hzoo** [comment]
👍 , some of the prs didn't have a github label so added

**Pull request merged**
