### PR TITLE
Add ignorePackages option

### PR DESCRIPTION
**Pull request by Marcosld**
## Description
Create a way to ignore certain packages when versioning or publishing with lerna.

## Motivation and Context
In https://github.com/lerna/lerna-changelog/issues/128#issuecomment-597693311 was mentioned if there was any way to ignore packages when versioning. I would also like to ignore some packages and not be prompted about versioning them when I run `publish` and `version`, even if these ignored packages or their dependecies have changes.

## How Has This Been Tested?
I added some tests to the project to check that my change was working. I also linked the lerna package and tested the changes locally in a dummy repository.

My changes shouldn't be affecting any other areas than `publish` and `version` commands.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Codermar** [comment]
Why was this not merged yet?

**Comment by Codermar** [comment]
I really need this feature... It is absolutely annoying how Lerna keeps me from publishing because it "finds" changes in a private package linked via submodule

**Comment by achingbrain** [comment]
This would be really useful. Please can it be merged?

**Comment by dilame** [comment]
I'm voting to merge it

**Comment by c10b10** [comment]
This is very useful.

**Comment by evocateur** [comment]
[v3.21.0](https://github.com/lerna/lerna/releases/tag/v3.21.0) added the [`--no-private` option](https://github.com/lerna/lerna/commit/a9b9f97457e4e4b0cac7f4ce562458d921a1f9be), is this not sufficient?

Other filtering of non-private version/publish is not going to fly, as this violates one of the core tenets of Lerna.

If a non-private package is still being published against your wishes, you have options such as making it private (`"private": true` in package.json), publishing more often so as to limit the scope of any given `lerna publish`, or removing the offending package from the monorepo entirely, as it clearly doesn't belong there if you're convinced it should not be versioned in coordination with the other monorepo siblings.

**Comment by Marcosld** [comment]
`--no-private` option serves the purpose on my end :)

**Comment by Codermar** [comment]
Sorry for the delay. It seems like the --no-private flag works to an extent for me.

**Comment by gdlm91** [comment]
What option do I have if I'm using Lerna with yarn workspaces, but I want to release one of the packages independently from the others? 

I can't seem to find a way to tell Lerna: "use workspaces,  except for this package/pattern"

**Pull request closed without merging**
