### PR TITLE
fix: drop strip-ansi in favor of native stripVTControlCharacters

### PR DESCRIPTION
**Pull request by mcmxcdev**
## Description
- uninstall `strip-ansi` dependency from multiple `package.json`
- replace `strip-ansi` import with `util.stripVTControlCharacters` in `wide-truncate.ts`
- replace `strip-ansi` import with `util.stripVTControlCharacters` in `index.spec.ts`

## Motivation and Context
References https://github.com/es-tooling/ecosystem-cleanup/issues/122

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (change that has absolutely no effect on users)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thank you @mcmxcdev! Looks like the snapshot change you made causes the tests to fail. Was that unintentional?

**Review by JamesHenry — CHANGES_REQUESTED** [review]
See comment

**Comment by JamesHenry** [comment]
I have marked this as a fix because it affects the runtime, and even though it should be like for like I think it's good to call it out in the release notes (which will happen automatically for a fix)

**Comment by mcmxcdev** [comment]
> Thank you @mcmxcdev! Looks like the snapshot change you made causes the tests to fail. Was that unintentional?

This was definitely unintenional and was caused by this setting in VSCode:

image

Not gonna solve it for every dev, but it might be a good idea to introduce a `settings.json` in the repo that disables this setting.

**Comment by JamesHenry** [comment]
Thank you @mcmxcdev!

**Pull request merged**
