### PR TITLE
Adds optional argument to specify master version when publishing

### PR DESCRIPTION
**Pull request by dijs**
Added so we could bypass user input during publishing.

### CODE REVIEW

**Comment by ahfarmer** [comment]
This change would really help me - any chance it can be merged @thejameskyle ?

I'm trying to use lerna in an automated publish system. (Alongside [commitizen](https://commitizen.github.io/cz-cli/) and [conventional-recommended-bump](https://github.com/stevemao/conventional-recommended-bump) )

**Comment by hzoo** [comment]
Since this skips user input it sounds like https://github.com/lerna/lerna/pull/135? I think we can close this in favor of that

**Comment by thejameskyle** [comment]
`--confirm` does not skip the input prompts, just the confirmations.

**Comment by hzoo** [comment]
Ok sounds good. Not sure we want to call it the `master version` although not sure I have better names - maybe even `--repo-version` or `--monorepo-version`?

**Comment by dijs** [comment]
So what is the change I need to make here?

**Comment by hzoo** [comment]
I'm just not sure about the name for the flag, and then also a test or to for the option would be nice

**Comment by hzoo** [comment]
Great, I think the last thing is to update the docs with the new option, maybe after https://github.com/lerna/lerna#--yes?

**Comment by dijs** [comment]
Done

**Comment by hzoo** [comment]
Awesome, thanks a lot! 🎉

**Pull request merged**
