### PR TITLE
use npm link for linking packages

### LINKED ISSUE #11: Nested directory support
I currently access packages like this `import { foo } from 'foo/bar';`. It seems the current bootstrap only creates `node_modules/foo/index.js` with `module.exports = require('/full/path/packages/foo');`. Thus when accessing `foo/bar`, it `Error: Cannot find module`. 

What would be the best path forward for supporting this? The only thing I can think of is to find all `*.js` paths and then create that path with matching exports.

### PR DESCRIPTION
**Pull request by zkochan**
I know it was done previously by making the symlinks manually. I did it using `npm link` and it works fine.

close #11

### CODE REVIEW

**Comment by rtsao** [comment]
This fixes https://github.com/lerna/lerna/issues/274, since actual `npm link` is used, right?

**Comment by zkochan** [comment]
Yes, it uses real `npm link` and it fixes that issue.

**Comment by eranimo** [comment]
This would be great. I'm having trouble with the fact that Lerna doesn't use actual symlinks

**Comment by longlho** [comment]
hmm this would definitely break cases where users don't have permissions to global `npm`.

**Comment by patrickheeney** [comment]
I am all for this, but not this exact implementation. In #11 I discovered that everyone needs a different _strategy_ because of different use cases. `npm link` has it's drawbacks that won't work for some. The existing behavior also won't work for some. In my testing I think this should be implemented as a strategy or a plugin into lerna. I think that is the only way to satisfy the different requirements.

**Comment by doug-wade** [comment]
> In #11 I discovered that everyone needs a different strategy because of different use cases

shouldn't prevent merging this pr.  when we fix #11, we can add the `strategy` flag -- getting any solution in that allows deep linking (i.e. `require('my-package/foo`);`) is better than getter a perfect solution that allow deep linking.

**Comment by patrickheeney** [comment]
In #11 I discussed the cons of `npm link` which this PR uses. I agree that getting in **any working** deep linking solution is better than getting in a **perfect** solution. However `npm link` has some issues, that in my opinion, will prevent it from working and cause more issues then it solves.

**Comment by rygine** [comment]
@patrickheeney @doug-wade I had a similar idea a while ago, but it didn't get any traction.

https://github.com/lerna/lerna/issues/215

**Comment by gigabo** [comment]
Hi @zkochan - Please take a look at #237.  Does that look like it would meet your needs?

**Comment by zkochan** [comment]
yeah, it should. I'll close this one

**Pull request closed without merging**
