### PR TITLE
feat: Add `lerna create` command

### PR DESCRIPTION
**Pull request by evocateur**
## Description

Porting over an internal tool I've been using for months now.

```
lerna create <name> [loc]

Create a new lerna-managed package

Positionals:
  name  The package name (including scope), which must be locally unique _and_
        publicly available                                   [string] [required]
  loc   A custom package location, defaulting to the first configured package
        location                                                        [string]

Command Options:
  --access        When using a scope, set publishConfig.access value
                             [choices: "public", "restricted"] [default: public]
  --bin           Package has an executable. Customize with --bin <binName>
                                                               [default: <name>]
  --description   Package description                                   [string]
  --dependencies  A list of package dependencies                         [array]
  --es-module     Initialize a transpiled ES Module
  --homepage      The package homepage, defaulting to a subpath of the root
                  pkg.homepage                                          [string]
  --keywords      A list of package keywords                             [array]
  --license       The desired package license (SPDX identifier)
                                                         [string] [default: ISC]
  --private       Make the new package private, never published to any external
                  registry
  --registry      Configure the package's publishConfig.registry        [string]
  --tag           Configure the package's publishConfig.tag             [string]
  --yes           Skip all prompts, accepting default values
```

## Motivation and Context

Fulfilling the promise of #485.

## How Has This Been Tested?

Lots of local testing, sufficient unit tests.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DavideDaniel** [comment]
hilarious commit messages... of course, this also makes me rethink my whole thought process that people don't really read all the commit messages... that or, I'm too involved...

**Comment by darrenjennings** [comment]
Shouldn't this be documented in the main readme?

**Comment by evocateur** [comment]
@DavideDaniel I have fun with commit messages that I know I'm squashing anyway.

The `loc` argument does need to match an existing package root location (default `./packages`), so if it's outside of those configured directories, it probably won't work. There is likely room for improvement on the messaging, in this context.

**Comment by evocateur** [comment]
@darrenjennings Yeah, it probably should be documented somewhere. There's a lot of documentation TODOs right now, which is among the largest pieces of work remaining before 3.0.0 leaves beta.

**Comment by jacefarm** [comment]
`from hell's heart, i stab at thee` 🤣

**Pull request merged**
