### PR TITLE
Include private packages in the list of updated packages

### LINKED ISSUE #570: Lerna stops working on packages when private: true
I'm on lerna 2.0.0-beta.36 and setting packages to `"private": true` disables Lerna for them altogether: no updates are detected, no bumping versions, nothing. A soon as I disable the `private` flag, Lerna works again.

I have tried to find this exact bug but didn't succeed. Sorry if it's a duplicate!

### PR DESCRIPTION
**Pull request by spudly**
Allows you to update versions in private packages, even if no public packages have changed. Fixes #570.

### CODE REVIEW

**Comment by spudly** [comment]
🎉🎉🎉

**Comment by oliverwoodings** [comment]
@hzoo any idea if a new beta release is going out soon? Sadly this PR hasn't made it into the latest beta release :(

**Comment by oliverwoodings** [comment]
Same with this PR: https://github.com/lerna/lerna/pull/672

**Comment by evocateur** [comment]
These are both available in the latest `lerna@canary`. I will do a release later today.

**Comment by oliverwoodings** [comment]
Thanks!

**Pull request merged**
