### PR TITLE
Remove --only-explicit-updates

### PR DESCRIPTION
**Pull request by thejameskyle**
Re: https://github.com/lerna/lerna/issues/706

### CODE REVIEW

**Comment by evocateur** [comment]
Pretty sure `yarn run fix` would make the tests pass

**Comment by wyuenho** [comment]
Hold on

**Comment by wyuenho** [comment]
In cf-ui, the packages are versioned independently. There's a graph of dependencies where updating one package often leads to whatever requires that to update, and whatever else requires that thing that requires that package you've changed and so on. Not using --only-explicit-updates often leads to more publishing errors in the case where someone accidentally bumped to a wrong version number on a dependee (what's the right word?) package, publishing that package, only then later find out that package wasn't ready to be published. So now 20 git tags and a few commits later, everyone's moaning about it's a PITA to roll back to the previous git state and still can't unpublish.

This is actually a very useful flag to prevents a lot of headache.

**Comment by thejameskyle** [comment]
@wyuenho Using `--only-explicit-updates` is exactly what got you in that scenario. You would not have had problems if you hadn't been using it because you would have been alerted to the fact that you were updating more packages than you intended.

**Comment by wyuenho** [comment]
> alerted to the fact that you were updating more packages than you intended

I'm not sure what this means. Correct me if I'm wrong, but a major version bump causes a cascade of dependee (sic) updates and I don't recall a way to tell lerna to skip those I really don't want to publish. Is there a way in lerna to NOT insist on publishing a package other than `--only-explicit-updates` that I'm not aware of?

**Comment by thejameskyle** [comment]
When you go to publish a set of updated packages, Lerna looks for the dependents because it needs to ensure that the packages stay in sync. Otherwise your repo ends up in a "dirty" state where Lerna is unsure if you intended to pin things to older versions. It will still link them, but they will fall behind (especially in independent mode).

If you didn't update dependents when making a major version bump, Lerna's linking would silently turn off and you'd have to go through and manually update everything.

The main reason that Babel wants to turn this off is because it exists in a world where npm2 is still in use by many of the project's users and deduping doesn't work as well as it should. The less versions of a dependency that exists the better deduping ends up working.

When you go to publish your updated packages `lerna publish` will let you know about all the packages being updated, including unchanged dependents. In independent mode it will also ask you to provide a new version for each updated package/dependent to be published.

The only time you should ever disable this behavior is when you want to manually pin a dependency to an older version of a package. The _only_ time you should want to do that is when you've made a breaking change and don't want to update everywhere yet. `--scope` and `--ignore` exist for this purpose. You can also manually pin a version range (which is what I would generally do).

Publishing new versions of packages and creating git tags are both really cheap to do. If you are using npm3 or Yarn you should never notice any problems with just publishing new packages all the time.

**Comment by wyuenho** [comment]
AFAICT `--scope` and `--ignore` do not work for `lerna updated` and `lerna publish`. They only work for run, exec, clean, ls and bootstrap.

> The only time you should ever disable this behavior is when you want to manually pin a dependency to an older version of a package. The only time you should want to do that is when you've made a breaking change and don't want to update everywhere yet.

That. This actually happens quite a lot when there are a lot of independent development going on where team members all need changes on different packages quickly. An all-or-nothing approach does not work for this style of development. The only way to publish a set of packages minus a few is to manually go in to the individual packages and type `npm publish`. This will of course still mess up lerna the next time around. There doesn't exist anything else that works for us except this wonderful feature.

**Comment by thejameskyle** [comment]
Just pin your versions, it works just fine.

**Comment by wyuenho** [comment]
This case come up from time to time:

- Module a1.0 depends on c^1.0
- Module b in your app depends on a^1.0 and c==1.0
- c introduce a breaking change for coworker foo, bumps to v2.0
- lerna publish bumps version of module a, the code that fixes the breaking change only qualifies as a minor update, so the module a1.1 and c2.0 go out
- There are now 2 versions of module c, one for the app, another for module a, dedupe in any npm or yarn won't work.

The only way to deal with this is really to pin to a@1.0 or update the app code to use c^2.0. But if module a also has something a release needs, the only option is to go fix the code to use c^2.0, which may push back the release for some time.

It would be nice if this feature is preserved, but we can try to adjust if you don't.

**Comment by hzoo** [comment]
Also this was only made for the fixed versioning scheme (Babel), and also means that if you make a breaking change in one package that is a dependency you make a breaking change in all of them (why we haven't made a breaking change in babel).

**Comment by wyuenho** [comment]
> if you make a breaking change in one package that is a dependency you make a breaking change in all of them 

So if the dep graph is A->B->C, if I bump C's major, the assumption in Lerna is B *also* might break, and we should bump B's major, and all packages that depend on B, and A, and all packages in the repo that depend on A?

I'm very confused. What's the point of allowing independent versions at all if we can't publish independently?

**Comment by hzoo** [comment]
I'm talking about the fixed versioning mode, never intended this flag to be used with independent mode (didn't think about it). I think the issue is that we don't know that if you bump a package A that is a dependency in B whether it is a major version or minor version.

**Comment by wyuenho** [comment]
It seems to me the problem is as James said, the symlinks and the fact that Lerna doesn't have any notions of "state snapshots" across publish events. Any invariant assumption violation confuses Lerna and makes recovery even more of a headache.

Just a last question, what's the exact behavior of `--force-publish`? Using the case [here](https://github.com/lerna/lerna/pull/707#issuecomment-288271305), if I force publish the C2.0 only, what would happen the next time I run `lerna publish` ?

**Comment by thejameskyle** [comment]
`--force-publish` adds packages to the publish, it does not exclude ones that will already be in it

**Comment by thejameskyle** [comment]
I'm going to merge this, if there needs to be a separate feature request for something to aid with pinning dependents to specific versions then that is a separate issue. `--only-explicit-updates` was not designed for that purpose and using it that way is incorrect.

**Pull request merged**
