### PR TITLE
Update dependencies and node version

### PR DESCRIPTION
**Pull request by Tallyb**
## Description
This PR updates multiple dependencies and their version. 
Removed support for node 8 (no longer LTS).  
Tested also against node 14. 

## Motivation and Context
For all the good reasons to keep packages up to date.

## How Has This Been Tested?
Making sure all CI tests are passing (and fixes where appropriate). 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ X ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ X] All new and existing tests passed.

### CODE REVIEW

**Comment by evocateur** [comment]
Prettier-related changes should be an entirely separate PR, for one thing.

**Comment by evocateur** [comment]
(Thank you for your patience, by the way! I've been swamped at work forever, and quite frankly a bit burned out by solo maintainership of a large project like Lerna. I _really_ appreciate the effort behind this PR, make no mistake)

**Comment by Tallyb** [comment]
Hi, 
Happy to help with maintenance. 
I will PR again with smaller PRs against the next branch. 
Can you pls bump it to latest master?

**Comment by evocateur** [comment]
[v4.0.0](https://github.com/lerna/lerna/releases/tag/v4.0.0) (now available as `lerna@next`) resolves this. Thanks for all your efforts!

**Pull request closed without merging**
