### PR TITLE
chore: Restore unmodified MIT license

### LINKED ISSUE #1618: Please register an SPDX License Exception
Note: I'm not here to express support for or against this license change, I just want to make some suggestions on the implementation of this change, which I think could be done better.

The [`"license"` property of package json][licenseprop] uses the [SPDX identifier][spdx_list] so that code can make algorithmic legal decisions based on a project's license. The recent change to the license file changes the license of the project so that it is no longer using the MIT license but since it is *mostly* using MIT and most companies are unaffected, the new value of `license` as `SEE LICENSE IN LICENSE` will cause most automated tools treat this as a custom license, which is good, but it can be better.

IANAL but I'd also point out that this license text as written does not allow for a company to change policy in order to adopt this software. If the goal is to affect behavioral change in the companies listed, the text should allow for companies that discontinue their relationship with ICE to adopt the existing releases of the software retroactively. Furthermore because this lists specific companies, it doesn't apply to companies who take on new associations to ICE. You may want to consider simply forbid companies that meet some criteria. 🤷‍♂️ 

## Expected Behavior

Project license should be interpreted as MIT with a license exception. Then companies with license verification tooling that are affected can correctly opt out and unaffected companies can ignore the exception.

## Current Behavior

Automated systems at unaffected companies that could approve an MIT license will reject this.

## Possible Solution

A [license exception](https://spdx.org/licenses/exceptions-index.html) should be [registered with SPDX](https://spdx.org/spdx-license-list/request-new-license). 

It could be something like `Abolish-ICE-Exception-1.0".

And the the license field should then be updated to `"license": "MIT WITH Abolish-ICE-Exception-1.0"`

This also allows other projects to compose other licenses with this exception. It's like code-reuse but for legalese.

[licenseprop]: https://github.com/lerna/lerna/blob/19a7f5d4bd88b9cc50b603adcf171623227ec554/package.json#L18
[spdx_list]: https://spdx.org/licenses/

### LINKED ISSUE #1622: Remove my contributions to Lerna
Due to #1616. I don't want to get into the politics of ICE of the enforceability of a license change, but as a past contributor I strongly condemn this type of toxic politicizing of the open source community and want no part in it.

Per https://github.com/lerna/lerna/pull/1616#issuecomment-416820399, I would like all my contributions removed. I will not be opening my own PR to do so.

@kittens @evocateur @jamiebuilds

### LINKED ISSUE #1630: Please remove jamiebuilds as maintainer for CoC violations
The statements in issues leveled at all employees of Palantir carte blanche appear to violate the Lerna code of conduct. Specifically: 

"Examples of unacceptable behavior by participants include the use of sexual language or imagery, _derogatory comments or personal attacks_, trolling, public or private harassment, insults, or other unprofessional conduct."

https://github.com/palantir/tslint/issues/4141
https://github.com/palantir/blueprint/issues/2877
https://github.com/palantir/blueprint/issues/2876

### PR DESCRIPTION
**Pull request by evocateur**
This reverts #1616

I would like to apologize to the Lerna community for a number of things, so I guess I'll start at the beginning. Above all, I appreciate your patience as I make mistakes and learn how to become a better open source maintainer.

First, I apologize for making the rash decision to support the addition of an unenforceable clause to the project's MIT license. I failed to accurately assess the _impact_ of this change, which led me to (incorrectly) focus on the _intent_. Despite the most noble of intentions, it is clear to me now that the impact of this change was almost 100% negative, with no appreciable progress toward the ostensible goal aside from rancorous sniping and harmful drama.

I am reverting the license changes. In the future, such changes (if any) will go through a much more thorough, completely public, and fair-minded process.

Second, I apologize for not enforcing the [Code of Conduct](https://github.com/lerna/lerna/blob/master/CODE_OF_CONDUCT.md) in a consistent and timely fashion regarding the membership of James Kyle in the Lerna organization. Despite his numerous (and appreciated) contributions in the past, it has been very clear for quite some time now that he has decided to cease making constructive contributions to the Lerna codebase as well as actively and willfully disregarding the code of conduct that [he himself added](https://github.com/lerna/lerna/commit/58748703da87e12a7ea80aa5379101a3206a5c52#diff-a1ee87dafebc22cbd96979f1b2b7e837) to the project.

Effective immediately, James Kyle has been removed from the GitHub org and will no longer have the privilege of making direct contributions to the source code.

Finally, I apologize to the community for not being a better communicator. I have done my best to be responsive to issues, but at the end of the day, larger concepts need longer explanations. Roadmaps need ...mapping? And so on. I would like to empower the community to contribute ideas and code that helps Lerna become the best monorepo manager it can be, and I can't do that by expecting strangers across the internet to read my mind.

To that end, I have created [Lerna Log](https://medium.com/lerna-log), a place to share patterns and explore the future of Lerna. Please let me know if there is anything else we can do to improve the experience of using Lerna. The first post will include details of organizational changes intended to help avoid these kinds of incidents in the future.

Closes #1622
Closes #1618
Fixes #1619
Fixes #1626
Fixes #1631
Fixes #1630

### CODE REVIEW

**Comment by Daniel15** [comment]
> To that end, I have created Lerna Log, a place to share patterns and explore the future of Lerna.

@evocateur - This sounds great! Is it possible to host it directly on the Lerna site rather than on Medium? Medium have a paywall after you've read a few posts, which is pretty annoying 😕

**Comment by TheLarkInn** [comment]
I think this would be a perfect github issue to open with RFC. @Daniel15 would you be willing to create one weighing the options. For example webpack's pages are all accessible without a paywall. Babel does their own, and they have tradeoffs worth mentioning! 🙇

**Comment by stefanpenner** [comment]
@evocateur thank you for the thoughtful response. Tricky situation!

**Comment by nickmccurdy** [comment]
@evocateur Thanks so much for your support, explanation, and professionalism. I'm sure this must have been stressful.

**Comment by hach-que** [comment]
@Daniel15 The paywall is only if the author opts into it explicitly for the story they are publishing, so this shouldn't be an issue.

**Comment by sarbbottam** [comment]
Thank you @evocateur and the lerna team!

**Comment by Daniel15** [comment]
>  The paywall is only if the author opts into it explicitly for the story they are publishing, so this shouldn't be an issue.

Ahh, interesting.

I still feel like it's better to own your own content, rather than some company hosting it on their domain. Anyways, I can create a separate issue for it 😃

**Comment by TheLarkInn** [comment]
@FuzzOli87 the sentiment is appreciated but please don't bring yourself to the same level with names and insults. But continue to bring great contributions and ideas to the project.

We'll have our Code of Conduct revised here in the coming days. Thanks.

**Comment by xtuc** [comment]
Thanks all :clap:

**Comment by petermikitsh** [comment]
To echo others, thank you @evocateur.

More broadly, a trend of political activism within OSS is something I feel many, including myself, would prefer not to see. It's been a relatively recent trend to see companies warming up to the open source community and beginning to contribute back too. Many contributors to open source projects also support themselves with professional software careers, and use open source software as part of their work. Situations like today could have shaken the faith in the open source community and the bridge between private enterprises and public software.

No doubt a tricky situation, but we can't discount the significance of this decision to support truly free and open software.

**Comment by Sieabah** [comment]
There must be a god.

**Comment by elizagamedev** [comment]
@petermikitsh Open source is inherently political. Dissuading political activism is a political act that favors the status quo.

**Comment by Sieabah** [comment]
@elizagamedev Protesting has its purpose and place, changing the license of an *open source* project is not the place. It has absolutely nothing to do with the political message and everything to do with modifying the license to be MIT with a list of exclusions curated by a single biased person.

Regardless of the politics or the bias, on either side, open source is primarily **open**. What James did was not *open* and needed to be undone.

**Comment by nickmccurdy** [comment]
Additionally the OSI, the leading authority on maintaining open source licenses, does not allow licenses to restrict usage for ethical or political purposes. A license must be usable without restrictions, or it is not an open source license.

https://opensource.org/faq#evil
> Can I stop "evil people" from using my program?
No. The Open Source Definition specifies that Open Source licenses may not discriminate against persons or groups. Giving everyone freedom means giving evil people freedom, too.

**Comment by tbredin** [comment]
Why can't you just protest the way the system you're protesting wants you to?

**Comment by Spotrealms** [comment]
Thank you for protecting the open source community by rolling back this harmful commit. This community does not need people violating licenses and free speech because it conflicts with their opinions or ideologies. Keep up the good work.

**Comment by Hurtak** [comment]
Exactly what parts of code of conduct did James Kyle broke?

**Comment by citypaul** [comment]
Thanks for the sanity @evocateur.

**Comment by PrinceMerluza** [comment]
Good result overall, this would serve as a precedent for similar issues in the future. Everyone should bookmark this or something.

**Comment by nickmccurdy** [comment]
@tbredin James' license change was legally flawed and would have not actually prevented those companies from using Lerna. There is a [LernaOpenSource](https://github.com/LernaOpenSource/LernaOpenSource) fork that was created which is legally usable by the blacklisted companies, but it's no longer necessary.

**Comment by TheLarkInn** [comment]
Before I go to bed for the night (last maintainer awake for now) 💤 😴 😂. I'm going to lock this thread so that it doesn't continue to escalate around ethical or political discourse. If there is anything unclear about the changes being made to the license, please feel free to submit it in a separate issue, but be wary of duplicates.

**Pull request merged**
