### PR TITLE
feat(version): add user-defined build metadata to bumped packages

### PR DESCRIPTION
**Pull request by rrhodes**
## Description
Adding support for [SemVer build metadata](https://semver.org/#spec-item-10) to Lerna version and publish commands.

* New `--build-metadata` string option added to Lerna version and publish commands.
* Build metadata validated against [SemVer specification](https://semver.org/#spec-item-10) and applied to new versions.
* Build metadata is applicable to both independent and fixed versioning.
* Metadata functionality added to `core/conventional-commits`
* Only case where `--build-metadata` is not permitted is when `--canary` is also used in publish command.

## Motivation and Context
This resolves [issue #2545](https://github.com/lerna/lerna/issues/2545), which myself and others have expressed an interest in.

## How Has This Been Tested?
Unit and integration testing provided in this PR. Tests should cover all new and altered logic. If that's not the case, let me know and I will be happy to fix that.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rrhodes** [comment]
Any feedback on this PR would be fully appreciated - this is my first contribution to Lerna. I'll investigate failing PR checks later this week.

**Comment by rrhodes** [comment]
Hello @evocateur, you're the most recently active member of the Lerna team I've found reviewing PRs. May you advise me who would be best to review this?

**Comment by rrhodes** [comment]
Hello @evocateur, may I be granted approval to run the repo workflows, please? Any feedback on this PR would be appreciated.

**Comment by rrhodes** [comment]
Hey @gigabo, @hzoo, @xtuc, and @ndelangen, sorry to ping you all out the blue. I see you also belong to [the Lerna org](https://github.com/lerna). This PR's been lingering for a while now - any feedback would be appreciated, please.

**Comment by rrhodes** [comment]
Hi Lerna org members (@evocateur, @gigabo, @hzoo, @xtuc, and @ndelangen), anyone available to review this PR, please? Or alternatively is there anyone else I should request reviews this?

**Comment by molivertsla** [comment]
@evocateur, @gigabo, @hzoo, @xtuc, and @ndelangen - also interested if we could get eyes on this please. If not, steps forward to add this functionality. Thank yoU!

**Comment by rrhodes** [comment]
Hi @jeffbcross, this PR was opened a while ago, before a change of ownership for the Lerna project. I've resolved recent conflicts against the `main` branch and would love feedback on this work if you may recommend any reviewers, please?

**Comment by JamesHenry** [comment]
Hi @rrhodes thanks so much for your patience, I'm sorry it sat in limbo for so long.

Please could we do the following:

- squash all the work so far down into a single commit and rebase against the latest main (at that point I will start reviewing)
- add proper e2e coverage via the relatively new approach (in this repo that is) of publishing the real lerna CLI to a locally running npm registry. You can see plenty of prior art in the relevant `e2e/version` project and you can see full instructions on running e2e tests in [CONTRIBUTING.md](https://github.com/lerna/lerna/blob/main/CONTRIBUTING.md)

**Comment by JamesHenry** [comment]
Please let me know if you have any questions regarding the e2e stuff once you have read those instructions

**Comment by rrhodes** [comment]
Hi @JamesHenry, no trouble, thanks for reviewing this. I may struggle to look into this in the coming weeks - currently in the process of moving house as well as all the usual Christmas fun at this time of year - but I can let you know when I've had an opportunity to review further.

**Comment by rrhodes** [comment]
Hi @JamesHenry, new E2E tests for the build metadata functionality added now.

**Comment by rrhodes** [comment]
Hey @JamesHenry, I agree, there are a lot of packages and I think it's great there's plans to reduce these. I've revised my PR now with your recommendation in mind to use `core/conventional-commits`.

**Comment by JamesHenry** [comment]
Thanks again @rrhodes - sorry, we needed to get the major codebase refactor over the line before addressing this one.

To save you having to try and figure it all out I have gone ahead and applied the rebase for you.

Once this is green we can get this merged!

**Comment by rrhodes** [comment]
Awesome, thanks @JamesHenry for your review and help toward this, great to see it release. 🚀

**Pull request merged**
