### PR TITLE
Use npm-lifecycle to run solitary lifecycle phases

### PR DESCRIPTION
**Pull request by evocateur**
## Description

Instead of shelling out to `npm run`, use [npm-lifecycle](https://www.npmjs.com/package/npm-lifecycle) and [npm-conf](https://www.npmjs.com/package/npm-conf) to run a single lifecycle phase instead of `npm run`'s automatically expanded list.

## Motivation and Context

#1292 pointed out that the `postversion` hook was being executed twice because we were calling `npm run version` _and_ `npm run postversion` for a given package (and the root) during `lerna publish`. This is obviously sub-optimal.

## How Has This Been Tested?

A bunch of new tests, as well as improvements to the existing tests in this area.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
Is this worth the native dependency?

**Comment by evocateur** [comment]
It does exactly what we want the same way npm itself does it, which is a huge win. What native dependency are you referring to?

**Comment by wtgtybhertgeghgtwtg** [comment]
I worded that really poorly and misunderstood the use.
It [depends on `node-gyp`](https://github.com/npm/lifecycle/blob/latest/package.json#L34) and then spawns a process that may or may not use that.  But since it doesn't seem to use it itself and just provides it like NPM does, I don't think it'll be a concern outside of really rare edge cases.
Sorry.

**Comment by evocateur** [comment]
No worries, thanks for clarifying!

**Pull request merged**
