### PR TITLE
feat: add json option to version command

### PR DESCRIPTION
**Pull request by amorscher**
Outputs projects which reveive a new version in json format.

## Description
Follwoing json format is supported:
```json
[
  {
    "name": "footer",
    "version": "0.0.4",
    "private": false,
    "location": "/home/ammo/git/lerna-getting-started-example/packages/footer",
    "newVersion": "0.0.5"
  },
  {
    "name": "header",
    "version": "0.0.4",
    "private": false,
    "location": "/home/ammo/git/lerna-getting-started-example/packages/header",
    "newVersion": "0.0.5"
  },
  {
    "name": "remixapp",
    "version": "0.0.4",
    "private": true,
    "location": "/home/ammo/git/lerna-getting-started-example/packages/remixapp",
    "newVersion": "0.0.5"
  }
]
```

## Motivation and Context
#3720

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (change that has absolutely no effect on users)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by fahslaj** [comment]
This is looking good @amorscher !

**Comment by amorscher** [comment]
@fahslaj I just wanted to add some more unit and at least one e2e test.

**Comment by amorscher** [comment]
Should be fine now.

**Review by fahslaj — APPROVED** [review]

**Comment by fahslaj** [comment]
Thanks @amorscher !

**Pull request merged**
