### PR TITLE
chore(link): enable strict type checking for link command

### PR DESCRIPTION
**Pull request by amorscher**
Removed some ts-ignore comments and any types

## Motivation and Context
Make link command lib more typesafe

## How Has This Been Tested?
Existing unit and regression test. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (change that has absolutely no effect on users)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by amorscher** [comment]
@JamesHenry @fahslaj  I don't know what the cause for the failing task is. Can anyone of you give me a hint?

**Comment by JamesHenry** [comment]
Sorry for the delay @amorscher please don't update this to the latest just yet, we want to do it later on our side when we can observe it in real time

**Comment by JamesHenry** [comment]
We will be rolling out a fix on Monday to address the issue with the CI runs, so I will take another look at this next week once that fix is available

**Comment by amorscher** [comment]
OK good. Just out of interest, do you have a clue what the problem for the ci is?

**Comment by JamesHenry** [comment]
@amorscher There was a bug with Nx Cloud which we have fixed today. Many thanks again!

Please hold fire on `add`, `bootstrap` and `link` commands now, they are being refactored

**Comment by amorscher** [comment]
@JamesHenry  Ok great!

So I am currently working on the version command which is quite a big one... 

Shall I create an Issue to track current work regarding type checking support?

**Pull request merged**
