### PR TITLE
chore(test): reactivate unit tests previously failing on windows os platform

### PR DESCRIPTION
**Pull request by amorscher**
Reactivates unit test which failed in the past

## Description
Reactivates unit test which failed in the past

## Motivation and Context
Re-activate ignored unit tests to achieve higher test coverage and regression testing.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (change that has absolutely no effect on users)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by amorscher** [comment]
Hmmm just got feedback from the ci runs... I reinstalled the import-command-spec filter as it seems to fail during ci run although it passes locally...

**Comment by amorscher** [comment]
Import command test will be handled in own pull request #3629

**Comment by fahslaj** [comment]
Looks like this PR has conflicts, but once those are resolved, we can merge it

**Comment by fahslaj** [comment]
Thanks @amorscher !

**Pull request merged**
