### PR TITLE
README: 2.x rewrite

### PR DESCRIPTION
**Pull request by hzoo**
~~Just started~~

- [x] https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.0

### CODE REVIEW

**Comment by thejameskyle** [comment]
Cool, thanks @hzoo I also started rewriting the intro here: https://github.com/lerna/lerna/compare/rewrite-readme

**Comment by hzoo** [comment]
Ok great, I can rebase my changes on top since I didn't really change the intro

**Comment by hzoo** [comment]
Ok I think that's everything? Need to combine the new/old intro and fixup stuff

**Comment by thejameskyle** [comment]
Hmm, yeah I want to find a way of pulling in the same markdown content. That doesn't need to happen in this PR though

**Comment by thejameskyle** [comment]
Actually I'm thinking we should centralize the documentation in the website repo. We can deal with translations there and it'd be better if everyone was linking to the same place. The one thing we lose is versioning.

**Comment by hzoo** [comment]
Ok if you want to move it over there we can do that - maybe we just leave the install/usage in the readme and a link to the website for more info?

**Pull request merged**
