### PR TITLE
[Feature] Added Callback to Command Run

### PR DESCRIPTION
**Pull request by kwelch**
Exposes a callback to be passed to the internal runCommand.

### CODE REVIEW

**Comment by gigabo** [comment]
Interesting... :thinking: 

@kwelch Could you provide some context here?  What does this patch provide?

**Comment by kwelch** [comment]
I am using lerna to manage a multi-page web app so each package is actually a section of the web app.

Specifically this is for a script at the top level that calls the `RunCommand`. I am looking to run the `build` script in each package and after all packages are build consolidate the artifacts into a single directory. 

This may be anti-pattern as it seem there has not been much work on the node api side to allow for use within a script file.

**Comment by gigabo** [comment]
I wouldn't call it an anti-pattern, but it's definitely not well supported right now.  I don't think it's part of the public API, either, so I worry a little bit about your relying on it. 😬 

Is there a way you could use the CLI instead in your workflow?

**Comment by kwelch** [comment]
I am going to try a post script, it is less ideal but agreed it is safer.

**Comment by kwelch** [comment]
Would a PR adding a public api be something that the lerna team would want?

Should be rather simple, just need a factory function around each of the classes that exposed commands. I would recommend also allowing for functionality from this PR of being able to add a callback to each command.

**Comment by gigabo** [comment]
Yes we definitely want a [public API](https://github.com/lerna/lerna/issues/167)!

Not sure I understand exactly what you're suggesting with the factory functions.

**Comment by evocateur** [comment]
A proper public API would go a long way toward disentangling the commands from their CLI particulars, for sure.

**Comment by kwelch** [comment]
Closing as this has had no progress.

**Pull request closed without merging**
