### PR TITLE
Document missing properties in lerna.json

### PR DESCRIPTION
**Pull request by XanderLuciano**
It seems that lerna.json is not fully documented anywhere? I found these settings throughout the github issues. Thought we should document them here for users to see along with a link to the example of how to use yarn's workspaces.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by XanderLuciano** [comment]
NPM is default client as per stated here: https://github.com/lerna/lerna/tree/master/commands/bootstrap#options

> The default `--npm-client` is `npm`.

**Comment by evocateur** [comment]
This is already documented here: https://github.com/lerna/lerna/tree/master/commands/bootstrap#--use-workspaces

Is that not sufficient?

**Comment by XanderLuciano** [comment]
That's sufficient, just seems like the documentation is extremely spread out and it's really hard to just find all the information.

That said, I don't use lerna normally, I'm just trying to learn how to use lerna so I can submit a PR to a project that uses lerna and it took me a long time to figure out everything. Seems like commands are in the documentation that don't exist in the CLI (like lerna version) so my intentions were to just make the information a little more consolidated. 

IMO it doesn't make sense to document properties of the JSON file in a documentation page about the CLI.

**Comment by evocateur** [comment]
I appreciate the effort to document, believe me.

I'm just not sure individual properties should necessarily be emphasized (especially non-universal ones) when it is the actual mechanism of "durable" configuration merging that is of interest. In other words, how CLI options are translated into a JSON configuration schema and merged with defaults.

**Comment by XanderLuciano** [comment]
No problem! That makes sense and I trust you understand the project better than I.

I think it makes sense to keep these separated since some are universal and some are not. It's likely the documentation structure makes more sense when you are starting fresh. It's just difficult to pickup and understand an existing project configured with lerna.

Thanks for the clarification!

**Pull request closed without merging**
