### PR TITLE
Fix (some) error repetition when running failing `npm run` script

### PR DESCRIPTION
**Pull request by nfcampos**
see discussion at #592 
see commit messages for details of changes

### CODE REVIEW

**Comment by nfcampos** [comment]
@evocateur  done

**Comment by evocateur** [comment]
@nfcampos Thanks! Now to investigate why the Travis build failed. -_-

**Comment by nfcampos** [comment]
@evocateur yeah im really not sure, it might be because of a unhappy combination of
  - jest running test files in parallel
  - jest re-using workers to do so
  - lerna tests relying on `process.pid` for temp path names
making it so on rare cases they somehow conflict with each other and two concurrent tests end up touching the same temp path

**Comment by evocateur** [comment]
Yeah, it probably was naïve of me to use the `process.pid`. I'll see what I can do to make that more robust. ([`yarn`'s method](https://github.com/yarnpkg/yarn/blob/master/src/util/fs.js#L761) seems pretty safe)

**Comment by nfcampos** [comment]
yes it does seem pretty safe

**Pull request merged**
