### PR TITLE
Issue 89: Added flag option --branch, for comparing with current last version.

### PR DESCRIPTION
**Pull request by Gongreg**
Added flag option --branch, which checks for changes between last tag in current branch (instead of current latest tag in whole repository), it allows to publish older versions of project. (Issue #89).

### CODE REVIEW

**Comment by thejameskyle** [comment]
Does the code from this comment not solve your use case? https://github.com/lerna/lerna/issues/89#issuecomment-200172189

**Comment by Gongreg** [comment]
I used your comment as a reference, 
```
git rev-list -n 1 $(git describe --tags) 
```

```
git rev-list -n 1 $(git describe --abbrev=0 --tags)
```

Only difference i had to add abbrev option.

**Comment by gigabo** [comment]
Oh, this is cool!

Does it even need to be an option?  Seems like it would be useful as _default_ behavior, maybe with a warning message if you're not currently on `master`?

**Comment by Gongreg** [comment]
I've added this as a option just for beginning (tried it out and it worked well for us), since tests for publish command looked like quite complicated. I could work on making it as a default behaviour/add message if you are not on master. :)

**Comment by Gongreg** [comment]
So should I follow up with doing something more about this? I agree that it could be default behaviour, didn't have a reason not to use it (it works same as before if you are on master, if you check older tag/branch/commit you expect it to work with last version, so I am quite confident that we can make this default behaviour). Also will someone check the tests after the changes? It was quite difficult to read your tests :)

**Comment by Gongreg** [comment]
Okay, I've made this execute as a default behaviour.
Also I've added check to see if user is inside some branch, because lerna publish needs to push to branch (shows error message if he is not in a branch).
Lerna updated works properly even when user simply checkouts older commit.

**Comment by spudly** [comment]
Any movement on this? I'd really like to see this become the default on branches and it looks like the only thing blocking the travis build is a few linter issues...

**Comment by Gongreg** [comment]
I'll fix the linter issues today/tomorrow. But I think this thing really needs tests if it is being done as default behaviour. I will inspect them more, I gave up too soon last time I looked into them. Also I've left the company I've worked in, I will contact them to allow me to update the code or I will reopen the PR from different fork.

**Comment by Gongreg** [comment]
Created new pr.

**Pull request closed without merging**
