### PR TITLE
[Feature] Add optionalDependencies

### PR DESCRIPTION
**Pull request by hzoo**
Fixes https://github.com/lerna/lerna/issues/121

### CODE REVIEW

**Comment by thejameskyle** [comment]
So optionalDependencies is supposed to make it so that the install does not fail if a optional dependency build fails. I'm not sure how to make that work here

**Comment by nolanlawson** [comment]
@thejameskyle Since that feature is usually designed for users rather than developers (e.g. user is on Windows 7 64-bit, developer is on Mac OS X), I think it would be fine for the time being if it just failed if the optional dependency fails.

**Comment by thejameskyle** [comment]
That seems like a poor experience when it goes wrong though

**Comment by gigabo** [comment]
This seems like a good first step.  If people start running into failures due to optional deps then it seems not hard to handle them separately during bootstrap and just warn on failure or something.

@hzoo - This LGTM. 👍

**Comment by bigtimebuddy** [comment]
Any updates on this PR? Would love to see it in?

**Comment by doug-wade** [comment]
I'd really rather we hold off merging this until we ensure that optionalDependencies are supported _as optional_, i.e. that `bootstrap` doesn't fail if they aren't installed.

**Comment by jstejada** [comment]
Any updates on this PR? Would love to see it in

**Comment by hzoo** [comment]
Not sure what to do with this, closing

**Comment by gtamas** [comment]
Would it be possible to reopen this issue?
Could you at least add support for this as an optional feature (disabled by default)? For example, how about adding a command line flag? That way this wouldn't cause any issues and people could enable it whenever they need it.

**Comment by evocateur** [comment]
We need to stop mangling the package.json so much during install, this is just a bandaid.

**Comment by a-magdy** [comment]
For those who are still looking for a solution

I pushed a lerna fork (w)ith (o)ptional (d)epdencies [lerna-wod](https://www.npmjs.com/package/lerna-wod) with the fix proposed in this PR

It is working for me locally but I had to use `npx lerna-wod` instead of `lerna` when I wanted to use it

Hope it helps

**Comment by MaxMilton** [comment]
Would have been nice to see this in the main package :cry:

**Comment by evocateur** [comment]
Implemented in b73e19df

**Pull request closed without merging**
