### PR TITLE
Fixes the progress bar not working

### PR DESCRIPTION
**Pull request by kentaromiura**
Fixes the progress bar not working and erroring when spawning lerna because stdout is not a TTY when called from process.spawn, node-progress was failing when trying to call this.stream.clearLine

### CODE REVIEW

**Comment by thejameskyle** [comment]
Should this maybe be fixed within node-progress?

**Comment by kentaromiura** [comment]
by looking at it node-progress seems to be an abandoned project

**Comment by thejameskyle** [comment]
I just got added to the project by tj, if you want to make a PR we can continue over there

**Comment by reggi** [comment]
What's the status here? Could this fix my issue?

https://github.com/lerna/lerna/issues/164

**Comment by kentaromiura** [comment]
I didn't follow-up because I fixed the problem by spawning the process with `{stdio:'inherit'}`, so that the progress bar receive a TTY;
I think it may fix your issue as it mocks the TTY commands needed by the progressbar

**Comment by hzoo** [comment]
What's up with this PR?

**Comment by gamtiq** [comment]
I have tested the fix in Windows (cygwin). It works fine.

**Pull request merged**
