### PR TITLE
Add a note about lerna-wizard.

### LINKED ISSUE #422: Lerna-wizard in readme
Hi, would you be interested in mentioning https://github.com/szarouski/lerna-wizard in readme? If answer is positive, I can make a PR. Thank you.

### PR DESCRIPTION
**Pull request by szarouski**
Resolves #422.

### CODE REVIEW

**Comment by gigabo** [comment]
Thanks @szarouski this looks cool to me.

That [gif is pretty big](https://github.com/szarouski/lerna/blob/3316ca135d5019584fd484aab2f75be9f94eaf7d/README.md#wizard), though.  @hzoo how do you feel about it?

**Comment by hzoo** [comment]
Yeah it's cool but right it could be made a lot shorter I feel?

**Comment by szarouski** [comment]
Sure, np. I'll make something shorter or just a screenshot. Will adjust PR soon. Thanks.

**Comment by szarouski** [comment]
Updated PR to point to png image instead. Please let me know if anything else should be improved and I'll take care of that. Thank you.

**Pull request merged**
