### PR TITLE
Add back proxy method of bootstrap with BootstrapProxyCommand

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by gigabo** [comment]
I wonder if we can do this without creating a new command?

Like, with an option in `lerna.json`?

```js
{
  "lerna": "2.0.0-beta.31",
  "proxy": true,
  ...
}
```

That way the bulk of bootstrap logic could be shared instead of duplicated.

Bug fixes / enhancements wouldn't need to be done in two places.

What do you think?

**Comment by evocateur** [comment]
I would think `bootstrapConfig` in `lerna.json` would be the natural place for such configuration, consulted in the existing BootstrapCommand when it decides how to "link" the sibling dependencies.

```json
{
  "lerna": "2.0.0-beta.31",
  "bootstrapConfig": {
    "proxy": true,
    "prefix": "/* @prefix etc */"
  }
}
```

I suppose you could make `bootstrapConfig.proxy` also accept `{ "prefix": "value" }` for slightly better config fluency (answering the question of "prefix for WHAT?" in the example above).

**Comment by hzoo** [comment]
I only wanted to add it back since projects had issues with the non-proxy method. I wasn't planning on doing any fixes for it at the time. Don't know

**Comment by hzoo** [comment]
Could make bootstrap take a flag as mentioned instead of a separate command if we still want this. closing

**Pull request closed without merging**
