### PR TITLE
changelog [skip ci]

### PR DESCRIPTION
**Pull request by hzoo**
Want to we want to put here to explain the issue/how it's solved?

cc @Gongreg, @spudly

### CODE REVIEW

**Comment by spudly** [comment]
I would just add the following:

This prevents unchanged packages from being republished when running `lerna publish` from a branch, which you might do if you're publishing a prerelease, or publishing a bug fix in an earlier release.

**Comment by Gongreg** [comment]
@spudly Added missing information. Don't have what else to add.

Also I didn't have a chance to thank you @spudly. So, Thank you! :)

**Comment by evocateur** [comment]
I rewrote the commit message when I merged it, I'm not sure why the changelog generator didn't pick that up: https://github.com/lerna/lerna/commit/d246667b9b8513d2c3ac14a796d9dc04126a1294

> We now check for changes since the most recent tag in the current branch, instead of the most recent tag in entire repository. This allows publishing older versions of a project in maintenance branches, as well as nightly releases from a feature branch.
>
> Additionally, we now ensure that the user is in a non-detached branch because we can't publish without a valid git branch.

**Comment by hzoo** [comment]
Yeah probably a bug - free free to edit/merge

**Comment by evocateur** [comment]
whoops, forgot `[skip ci]` 😿

**Pull request merged**
