### PR TITLE
lerna publish --skip-git supported in non-git repository

### PR DESCRIPTION
**Pull request by vrachels**
## Description
This change overrides Command::requiresGit in PublishCommand::requiresGit and adds a check of that property in the collectUpdates utility function.

## Motivation and Context
lerna publish --skip-git fails if the current directory is not a git repo, because validation and supporting functions are not being notified of the --skip-git state

## How Has This Been Tested?
Used publish --skip-git in our repository that was recently moved from git -> p4 that has many subpackages.
Used again with --skip-git --skip-npm to confirm consecutive updates of packages.
Ran npx jest: 
 running from 3.0.0-alpha.1 got 2 failed tests
 with patch fails 14 tests, 9 snapshots

looks like there are definitely issues, but seems like a deeper problem
first (new) failed test, for example, is
```
Command › .filteredPackages › --since should return packages updated since the last tag
Expected value to have length:
      2
    Received:
      ...
      5
```
and others relating to git history / diff features.

noted below that this could be a breaking change, but not that invested in this to determine what is the problem with the broken git features.  I don't mind following up if there are suggested additional changes to try.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by evocateur** [comment]
As I already noted just today in #1293, `--skip-git` is a misleading option name, as it only skips the commit and push, not _all_ git operations.

**Comment by vrachels** [comment]
And yet it's still a useful feature/tool without git, and didn't require major changes to get it working.

**Comment by evocateur** [comment]
It cannot choose the correct packages to publish, thus it is worthless without git.

**Comment by vrachels** [comment]
Er, It was able to update and publish all packages.  I don't see that as worthless.  Heavy-handed, perhaps, and not the greatest long term solution, but definitely still useful to our project.

Especially with --scope capability, we can manually do (or write our own tooling to do) the only-publish-what-is-updated task.

**Comment by evocateur** [comment]
You can’t scope publishes.

**Comment by testower** [comment]
The rejection of this PR seems a bit harsh. I can easily see use cases for this, in cases where in CI git is not available, just the cloned project files. npm is perfectly capable of publishing packages without the presence of git, why not lerna? If I know the version, why can't I simply provide it as an argument? And if the default behavior of lerna is to update all packages, whenever one of them changes (non-independent), this doesn't seem like a far-fetched addition.

**Comment by evocateur** [comment]
1. That’s not how lerna publish works.

2. If you “know the version”, what’s stopping you from looping through the packages and running `npm publish` yourself?

**Comment by testower** [comment]
1. Not really sure what you mean. I clearly can provide it with a version of my own as my workaround demonstrates:

```
git init . && lerna publish --skip-git --force-publish=* --repo-version $(node -e \"console.log(require('./package.json').version)\") --yes
```

2. Absolutely nothing is stopping me from doing everything myself, except it would not be very fruitful for me to reinvent the wheel.

**Comment by evocateur** [comment]
> if the default behavior of lerna is to update all packages

This was the quote I was responding to. That's not how `lerna publish` works.

"[Updating] all packages" is a _side-effect_ of having no existing tags. The "normal" publish process depends on git for determining what has changed since the last release (signified by an annotated git tag), and _only_ publishes the packages that have changed since then.

**Comment by testower** [comment]
I understand, thanks for clarifying. I have misunderstood the distinction betweeen fixed/locked and independent modes and assumed in fixed/locked, all packages would be updated regardless. Of course I see now that this is not the case, and explains why I needed `--force-publish=*` in my workaround.

That said, I read some recent discussions around version 3 of lerna, where you indicate that you intend to split version from publish. I see this as another indication that versioning is git business and publishing is npm business. You also mentioned that lerna version would likely be called by lerna publish. So an approach could be to allow a --skip-version.

My workaround is not pretty, and perhaps illustrates why I should roll my own in this particular case. It's just that I found lerna useful to manage my mono-repo, but I had odd requirements during publishing. I appreciate that you cannot accommodate every peculiar use case.

**Comment by testower** [comment]
Although I'm finding this odd:

> 2. If you “know the version”, what’s stopping you from looping through the packages and running `npm publish` yourself?

Given this comment I'm curious about why there is a --repo-version argument:

```
When run with this flag, publish will skip the version selection prompt and use the specified version. Useful for bypassing the user input prompt if you already know which version to publish.
```

**Comment by testower** [comment]
For anyone interested I ended up doing this:

```
// CI has already bumped version in root package.json,
// so first we replicate that in all the packages with lerna exec
lerna exec -- npm version $(node -e \"console.log(require('./package.json').version)\")

// Then run npm publish in all the packages
lerna exec -- npm publish
```

**Pull request closed without merging**
