### PR TITLE
Use sync-exec for node 0.10

### PR DESCRIPTION
**Pull request by hzoo**
If we are going to support node 0.10

- 0.10 doesn't have child_process.execSync

---

Fixes https://github.com/lerna/lerna/issues/157

### CODE REVIEW

**Comment by thejameskyle** [comment]
Sure, want to add 0.10 to the travis.yml?

**Comment by hzoo** [comment]
Ok - maybe later we can do the same as babel and setup circleci to run 0.10, or move on of those to appveyor for windows

**Comment by hzoo** [comment]
added circle ci for 0.10 as alternative - failing test is just a timeout

**Comment by thejameskyle** [comment]
Why circle ci?

**Comment by hzoo** [comment]
Just doing what we did in babel (don't have to)

**Comment by thejameskyle** [comment]
Yeah, I don't want circle ci for no reason. I'd rather just add 0.10 to the list of travis versions.

**Pull request merged**
