### PR TITLE
docs: note some disadvantages with hoisting

### PR DESCRIPTION
**Pull request by joeytwiddle**
## Motivation and Context
Before enabling an option, I want to know what are the advantages and disadvantages of doing so.

## Description
Documented one possible disadvantage of hoisting:

- Accidentally require-ing a common dependency without adding it to `package.json`

## How Has This Been Tested?
I created three packages, two with a common dependency, and one without.

The third without was still able to require the common dependency, although it had not specified it in its `package.json`.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Additional
If there are any disadvantages which are not documented here, please let me know. I may be able to add them.

### CODE REVIEW

**Comment by bertho-zero** [comment]
You can spot these errors with eslint.

**Comment by joeytwiddle** [comment]
@bertho-zero Is this the plugin that can warn about that? [eslint-plugin-dependencies](https://github.com/zertosh/eslint-plugin-dependencies) If so I will add a link to it.

**Comment by bertho-zero** [comment]
It's this plugin: https://github.com/benmosher/eslint-plugin-import

**Comment by joeytwiddle** [comment]
That looks great, thank you~

**Comment by wbern** [comment]
This is a very valid hint. I really want more information like this when it comes to lerna, so I know why the import works even though I feel like it shouldn't.

**Comment by andrewcharnley** [comment]
Agree. Also many npm commands won't work - npm outdated and npm audit being two.

Also should compare 'lerna link convert'. See https://github.com/lerna/lerna/issues/1788

**Pull request merged**
