### PR TITLE
Handle spaces in paths correctly

### PR DESCRIPTION
**Pull request by motiz88**
This fixes the many test failures I encountered with lerna checked out at a path containing spaces.

### CODE REVIEW

**Comment by motiz88** [comment]
Sorry, another change snuck in. Will reorganize the branch and reopen.

**Comment by motiz88** [comment]
Hmm. this fails because `command-join` requires Node >= 4. What is the official line on Node version support here in Lerna?

**Comment by hzoo** [comment]
Right now it's node 0.10 but we could remove support since support is ending. I mostly kept it since babel supports node 0.10 still

**Comment by thejameskyle** [comment]
@motiz88 are you going to change the dependency to https://github.com/motiz88/command-join/commit/41dfad5710bd29770ece5fb18ff076619128c8db?

**Comment by motiz88** [comment]
@thejameskyle That was the idea but it's not done yet. Is that the course of action you prefer for now?

**Comment by thejameskyle** [comment]
If you get blocked on merging that into the main project you can do that, I would try making a PR first to see how they respond

**Comment by motiz88** [comment]
https://github.com/seangenabe/command-join/pull/1

**Comment by motiz88** [comment]
With seangenabe/command-join#1 merged, this now works on 0.10 and 0.12 too.

**Pull request merged**
