### PR TITLE
fix(version): update lock files after the version hook

### PR DESCRIPTION
**Pull request by matheo**
## Description

Right now the lock-file is updated before the root `version` script, but if we edit some custom stuff in that hook (with `lerna exec --since` then it won't be possible to include those changes in the lock file and that seems undesirable.

## How Has This Been Tested?

Tested locally with a custom hook updating the package.json files of the changed packages.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (change that has absolutely no effect on users)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by matheo** [comment]
@fahslaj the CI failed in a non-related test it seems :thinking:

**Review by fahslaj — APPROVED** [review]

**Comment by fahslaj** [comment]
Thanks @matheo !

**Comment by matheo** [comment]
Thanks @fahslaj any ETA for the release?

**Comment by fahslaj** [comment]
No specific ETA yet, but we are working on a minor release that will hopefully be out early this coming week.

**Comment by fahslaj** [comment]
@matheo this was just released with version 7.4.0

**Comment by matheo** [comment]
@fahslaj Thanks!

**Pull request merged**
