### PR TITLE
Add coverage report

### PR DESCRIPTION
**Pull request by doug-wade**
In response to https://github.com/lerna/lerna/pull/574#issuecomment-277347146

### CODE REVIEW

**Comment by gigabo** [comment]
Whoa, speedy @doug-wade is speedy. 🚀

**Comment by gigabo** [comment]
What would we have to do to get a GitHub integration for this and see it in PRs?

**Comment by doug-wade** [comment]
I use [codecov](https://codecov.io/) for that, which adds a [summary to pull requests](https://github.com/doug-wade/idd/pull/64#issuecomment-261154176), but not a full coverage report.  I can set that up over the weekend if that's what we want.  The other provider I've used in [coveralls](https://coveralls.io/), but codecov is newer and newer is always better :wink:.

**Comment by hzoo** [comment]
Babel uses codecov https://github.com/babel/babel/commit/db67d7fdce4feed8c2a1aaa4ee353eb4fd60a5df also does es6 coverage

**Pull request merged**
