### PR TITLE
fix(version): pass `--atomic` to `git push`

### LINKED ISSUE #2392: Use `--atomic` when running `git push` in `lerna version`
Currently, `lerna version` will push repository by [`git push --follow-tags`](https://github.com/lerna/lerna/blob/master/commands/version/lib/git-push.js#L11), which defaults to non-[atomic](https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-atomic), that could cause problems in certain situations.

E.g., when somebody else pushed new commits to origin/master during one running `lerna version`.

## Expected Behavior

Do an atomic pushing when running `lerna version`.

## Current Behavior

Tags are pushed, but master is rejected. These orphan tags need to be manually deleted, to avoid conflicts in future.

## Possible Solution

Use `git push --follow-tags --atomic` (which is supported since git [v2.4.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.4.0.txt#L70)).

## Steps to Reproduce (for bugs)

1. Fetch and pull newest master.
2. Run `lerna version`.
3. Somebody else pushed new commits to master.
4. Check `yes` in the prompt of `lerna version`.
5. Result: changes made and tags pushed, but master rejected.
6. Delete all these *orphan tags*.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "libs/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "stream": true,
  "useWorkspaces": true,
  "conventionalCommits": true,
  "command": {
    "publish": {
      "npmClient": "npm",
      "allowBranch": "master",
      "verifyAccess": false,
      "message": "chore(release): publish",
      "registry": "https://registry.npm.easyops.local"
    }
  }
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.12.0 |
| `yarn --version` | 1.17.3 |
| `node --version` | 12.13.0 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.1 |

### PR DESCRIPTION
**Pull request by weareoutman**
Fix #2392

## Description

Pass `--atomic` to `git push`. See [git's doc](https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-atomic)

## Motivation and Context

As #2392 said.

## How Has This Been Tested?

Tested manually.

```
% git push --follow-tags --atomic --no-verify origin master
error: atomic push failed for ref refs/heads/master. status: 2

fatal: the remote end hung up unexpectedly\nTo git.easyops.local:anyclouds/next-libs.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@git.easyops.local:anyclouds/next-libs.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by weareoutman** [comment]
It's weird that CI is failed with:

```
Summary of all failing tests
FAIL commands/publish/__tests__/publish-canary.test.js (12.797s)
  ● publish --canary sequential › 3. source
    Command failed: git describe --always --long --dirty --first-parent --match package-1@*
    fatal: .git/index: index file open failed: Permission denied
      at makeError (node_modules/execa/index.js:174:9)
      at node_modules/execa/index.js:278:16
          at runMicrotasks (<anonymous>)
Test Suites: 1 failed, 37 passed, 38 total
Tests:       1 failed, 254 passed, 255 total
Snapshots:   54 passed, 54 total
```

Seems this PR has nothing to do with it.

**Comment by evocateur** [comment]
Yeah, the Windows tests are flaky due to environmental issues. I kicked it again and it passed. /shrug

**Comment by evocateur** [comment]
Thanks!

**Comment by amirburbea** [comment]
We need an option to disable this as azure devops git apparently does not support atomic push

```
lerna info execute Skipping releases
lerna info git Pushing tags...
lerna ERR! Error: Command failed: git push --follow-tags --atomic --no-verify origin master
lerna ERR! fatal: the receiving end does not support --atomic push
lerna ERR!
lerna ERR!     at makeError (C:\Workspace\beacon\node_modules\execa\index.js:174:9)
lerna ERR!     at C:\Workspace\beacon\node_modules\execa\index.js:278:16
lerna ERR! lerna Command failed: git push --follow-tags --atomic --no-verify origin master
lerna ERR! lerna fatal: the receiving end does not support --atomic push
lerna ERR! lerna
```

**Comment by evocateur** [comment]
@amirburbea That's fair. Probably should be resilient to this type of failure and re-attempt without the `--atomic` flag, since the local version of `git` won't always correspond to the remote's.

**Comment by evocateur** [comment]
@amirburbea Fixed in [v3.20.1](https://github.com/lerna/lerna/releases/tag/v3.20.1)

**Comment by amirburbea** [comment]
Wow! That's fast. Thanks.

**Comment by wickedest** [comment]
Are you sure that's fixed in v3.20.1?  I am seeing that version fail: `error: unknown option `atomic'`.

**Comment by paulocmoreno** [comment]
@evocateur, I am sorry to mention you in a closed issue but today I updated to lerna 3.20.2 and the error below broken my build. I want to give you more context to reconsider the amirburbea's suggestion to add an option to disable the atomic flag.

```
lerna ERR! Error: Command failed: git push --follow-tags --no-verify --atomic origin master
lerna ERR! fatal: the receiving end does not support --atomic push
lerna ERR! fatal: the remote end hung up unexpectedly
```

This error occurred in a Windows 2019 Server using Azure Pipelines. At line https://github.com/lerna/lerna/commit/6f0e2bb1b033b0579910cedcf0be84f1474c1580#diff-4a3a3aa992c599b130c66225bed2e8f4R16 lerna searchs for "atomic" on stderr. This is the expected default behavior of git but it can be changed using the environment variable GIT_REDIRECT_STDERR. This is a valid option for git and it is used to workaround a new behavior of Windows Server 2019 where it handles messages on stderr as errors. More details about this in https://github.com/microsoft/azure-pipelines-image-generation/issues/740 and https://github.com/dahlbyk/posh-git/issues/109. In practice, lerna is not more compatible with Azure Pipelines on Windows Server 2019 and the suggested option can restore this compatibility. For now, I have reverted to an older version of lerna. Thanks for your attention and for this great project.

**Comment by evocateur** [comment]
@paulocmoreno Ok, I suppose we should check `process.env.GIT_REDIRECT_STDERR` before testing the output? A PR would be very appreciated.

**Comment by paulocmoreno** [comment]
@evocateur I created https://github.com/lerna/lerna/pull/2467 for your consideration. Thanks for your attention.

**Pull request merged**
