### PR TITLE
upgrade octokit to v17

### PR DESCRIPTION
**Pull request by hipstersmoothie**
## Description

See title

## Motivation and Context

v17 has been out for awhile and this will help tool built on top of lerna to upgrade as well

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by gr2m** [comment]
you should be good to go once you update your lock file:
https://github.com/octokit/endpoint.js/releases/tag/v6.0.2

**Comment by hipstersmoothie** [comment]
All types have been updated! Just need to test this out with a project locally. @evocateur is there a specific command that hits this octotkit util?

**Comment by evocateur** [comment]
[v4.0.0](https://github.com/lerna/lerna/releases/tag/v4.0.0) (now available as `lerna@next`) should resolve this, as we upgraded to v18 of `@octokit/rest`. Apologies for the delay, and thanks for the effort!

**Comment by hipstersmoothie** [comment]
Thank you! Now i'm excited for v4 😄

**Pull request closed without merging**
