### PR TITLE
Run pre/post install scripts during bootstrap

### LINKED ISSUE #73: lerna bootstrap for a single (new package)
We probably don't want to `lerna bootstrap` each each we create a new package so it should just `npm install` and link up that new package?

### PR DESCRIPTION
**Pull request by seansfkelley**
Fixes #73, #279. Lays some groundwork for #342.

### CODE REVIEW

**Comment by seansfkelley** [comment]
The AppVeyor build failure with (transient?) permissions issues, but I'm not sure how to retrigger.

**Comment by seansfkelley** [comment]
ping @hzoo @thejameskyle, thoughts?

**Comment by seansfkelley** [comment]
@hzoo / @thejameskyle thoughts? Having this behavior would make my life a lot easier for my Typescript-based project.

**Comment by thejameskyle** [comment]
Thanks

**Comment by seansfkelley** [comment]
Thanks for merging!

**Pull request merged**
