### PR TITLE
Preserve existing deps with lerna add

### PR DESCRIPTION
**Pull request by marionebl**
Adresses #1099

### CODE REVIEW

**Comment by evocateur** [comment]
Thanks so much for the quick turnaround!

**Comment by marionebl** [comment]
@evocateur No worries! I want to make things better by contributing, so fixing stuff I broke is high priority. Hope this is solid now.

**Comment by evocateur** [comment]
augh Windows failed due to a permissions error in the npm cache. Whatever, it passes locally, I'ma merge it.

**Comment by marionebl** [comment]
Thanks @evocateur for the fast merge/response time!

**Comment by evocateur** [comment]
Published in https://github.com/lerna/lerna/releases/tag/v2.5.1

**Pull request merged**
