### PR TITLE
fix(run): missing `fs-extra` dependency declaration

### PR DESCRIPTION
**Pull request by fupengl**
## Description

The `fs-extra` dependency is missing when `lerna run` is executed. 
This dependency must be declared and installed

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (change that has absolutely no effect on users)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by fupengl** [comment]
> Thanks @fupengl, but what issue/error have you actually observed please?
> 
> `@lerna/run` depends on `@lerna/profiler` which already depends on `fs-extra` so the dependency is already transitively available.
> 
> I understand the desire for correctness, and that's fine, but it would first be good to understand if this actually caused any issues in practice

If the non-dependency upgrade is used, the module will still not be found. It is recommended to add it. The currently added version is the same as the version number that @lerna/profiler depends on, and there will be no additional impact.

**Comment by fupengl** [comment]
> Thanks @fupengl, but what issue/error have you actually observed please?
> 
> `@lerna/run` depends on `@lerna/profiler` which already depends on `fs-extra` so the dependency is already transitively available.
> 
> I understand the desire for correctness, and that's fine, but it would first be good to understand if this actually caused any issues in practice

**Comment by fupengl** [comment]
My problem is that the dependencies installed through pnpm show that the package cannot be found when executing the run command

**Comment by JamesHenry** [comment]
@fupengl ok cool thanks, I wondering if it might turn out to be a pnpm thing... We can definitely merge this once it's green

**Review by JamesHenry — APPROVED** [review]

**Comment by fupengl** [comment]
If it is a case of non-dependent promotion, it needs to be solved by lerna

**Pull request merged**
