### PR TITLE
added style sheet handling for "styles.css"

### PR DESCRIPTION
**Pull request by boxxxie**
#311

### CODE REVIEW

**Comment by gigabo** [comment]
Hi @boxxxie - Thanks for taking this on!

Looks like travis is failing with some linter violations:

image

You can run the linter locally with `npm run lint`.

**Comment by boxxxie** [comment]
this pr is finished,  unless you request something more

**Comment by boxxxie** [comment]
i don't understand the error i'm getting. it's a windows error, and the error message makes it seem like it has nothing to do with my code

**Comment by boxxxie** [comment]
fixed on different pr

**Pull request closed without merging**
