### PR TITLE
Upgrading @zkochan/cmd-shim to 5.0.0

### PR DESCRIPTION
**Pull request by mesner**
Upgrading @zkochan/cmd-shim to 5.0.0.   

## Description
Change of version within package.json files for the root project and for utils/create-symlink.

## Motivation and Context

We discovered that symbolic links were not being created for a local repository when running `lerna add projectChild --scope=projectParent --loglevel=silly`, with no errors being reported.   Investigation revealed that the promise returned from creating a 'binary' symbolic link (type='exec') in a prior project dependency using the cmd-shim was never being resolved or rejected (windows 10 64 bit running git bash), which halted progress of the pMapSeries in symlink-dependencies, causing early termination.  Upgrading to the latest version of cmd-shim resulted in the successful resolving of the promise and allowed the linking to complete, which itself resulted in creating the link to our projects above.

## How Has This Been Tested?

`npm run test` from a fresh checkout of master results in 829 linting problems due to missing node_module directories in subpackages.  I was able to force a global install of lerna to run lerna bootstrap on this project, but this didn't resolve the issue.

`npm jest` results in all tests passing.

`npm run integration` results in 2 publishing failures.

I'd be happy to try to resolve these test failures, but my suspicion is that they are unrelated to my dependency upgrade.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by yoitsro** [comment]
@evocateur Is there anything we can do to push this forward? Just run into the issue myself 😭

**Comment by revelt** [comment]
Is this PR a redundant in light of of https://github.com/lerna/lerna/pull/2473 ? That PR replaces `@zkochan/cmd-shim` with `cmd-shim`.

**Comment by armano2** [comment]
Currently there is issue with upgrading dependencies as lerna still supports node 6 (even if not tested in CI)

we can't upgrade this package without changing required node version, personally i think that lerna should upgrade requirements to node 10 as everything lower than that is no longer maintained. 

this will unlock upgrade of a lot of dependencies not only this one

https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true
https://nodejs.org/en/about/releases/

**Comment by evocateur** [comment]
[v4.0.0](https://github.com/lerna/lerna/releases/tag/v4.0.0) (now available as `lerna@next`) should resolve this, apologies for the delay.

**Pull request closed without merging**
