### PR TITLE
Publish: Add a `diff` flag

### PR DESCRIPTION
**Pull request by koddsson**
## Description

This patch basically takes some lines from `DiffCommand` and executes
them if the `--diff` flag is set.

## Motivation and Context

When using lerna sometimes I want to know the code that lerna is about
to publish to help me figure out the version I would like for it to be
published as.

## How Has This Been Tested?

I some manual testing of this after looking at the tests for publish and it worked fine for me when independent publishing. I proceeded to add some tests for normal and independent mode but they are sadly both failing and I'm not sure on what's wrong with them. Any pointers here would be great 😊

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by evocateur** [comment]
I don't believe saddling `lerna publish` with yet another flag is worth the added complexity, in this case. I'd rather improve the existing `lerna updated` and `lerna diff` commands to suit this purpose.

**Comment by koddsson** [comment]
@evocateur No worries!

Is there a way you can think of that I can achieve what I want in lerna (which is just getting the package diff when selecting the version) or should I just hack together a bash command?

**Comment by koddsson** [comment]
I'm actually not sure I can do this in a bash script. There's stuff I'd need to do like `--no-pager` so I can print the git diff output but maybe I can add those options to the diff command.

But maybe I'm the only one that wants this flag 😅

**Comment by evocateur** [comment]
@koddsson Would `lerna diff <packageName>` in a separate shell work? If you pass `--no-pager`, that seems like a bad experience when you've got more than a page worth of diff...

**Comment by koddsson** [comment]
Yeah I think that's probably the most simple solution. I'll close this, thanks for your time!

**Comment by evocateur** [comment]
Thanks for understanding!

**Pull request closed without merging**
