### PR TITLE
fix: Install from Private Enterprise Repositories (#1539)

### PR DESCRIPTION
**Pull request by jd-carroll**
Fix installing packages when a private enterprise repository is configured.

(Note: I am using `npm@6.3.0` and I am having issues getting the `package-lock` to install correctly.  I believe lerna recently moved to a mono-repo style itself, but I wasn't able to figure out how to use the lerna tooling on itself.  Any guidance appreciated)

### CODE REVIEW

**Comment by jd-carroll** [comment]
Another note: I believe the checks failed for the same reason I am having difficulty.  Happy to tweak as necessary.

**Comment by evocateur** [comment]
Your package has _runtime_ dependencies on jest and ts-jest. That's not gonna fly.

Also, where is the source code? No `homepage` field in package.json means I can't locate its source, and I'm not in the habit of accepting dependencies I can't read first.

**Comment by jd-carroll** [comment]
@evocateur Thanks for pointing that out, def a mistake and will get that fixed tonight!

**Comment by jd-carroll** [comment]
@evocateur I've updated `package-metadata`, could you take a look?  I'm open to other thoughts on node module, most interested in getting the functionality in

**Comment by evocateur** [comment]
This should be fixed in [v3.1.1](https://github.com/lerna/lerna/releases/tag/v3.1.1).

**Pull request closed without merging**
