### PR TITLE
feat!: migrate to nx 17.1

### PR DESCRIPTION
**Pull request by fahslaj**

### CODE REVIEW

**Comment by JamesHenry** [comment]
@jasmin2014 It’s not the best idea to ask questions on closed PRs, particularly as this PR is not related to what you are asking about.

Please review https://lerna.js.org/docs/legacy-package-management

**Comment by jasmin2014** [comment]
> @jasmin2014 It’s not the best idea to ask questions on closed PRs, particularly as this PR is not related to what you are asking about.
> 
> Please review https://lerna.js.org/docs/legacy-package-management

Thank you for your answer, but I have reviewed this document and it does not solve my doubts, so I am taking the liberty of asking a question here

**Comment by JamesHenry** [comment]
The big shift in thinking here is that lerna has _zero_ involvement in your dependency management within your workspace. Your usage of your package manager is therefore no different when lerna is present or not. Therefore your question is actually about how to use npm workspaces.

Here is a working example:

https://stackblitz.com/edit/stackblitz-starters-vjwvke?file=package.json

If you run `npm list` you can see your workspaces (defined by the workspaces property in the root package.json):

```sh
npm list 
node-starter@ /home/projects/stackblitz-starters-vjwvke
+-- a@ -> ./packages/a
| `-- chalk@5.3.0
`-- b@ -> ./packages/b
  +-- a@ deduped -> ./packages/a
  `-- chalk@5.3.0 deduped
```

I had added chalk as a dependency to both packages simultaneously by running:

```sh
npm i chalk -w a -w b
```

And as you can see by the resulting workspace it worked just fine

**Comment by jasmin2014** [comment]
> The big shift in thinking here is that lerna has _zero_ involvement in your dependency management within your workspace. Your usage of your package manager is therefore no different when lerna is present or not. Therefore your question is actually about how to use npm workspaces.
> 
> Here is a working example:
> 
> https://stackblitz.com/edit/stackblitz-starters-vjwvke?file=package.json
> 
> If you run `npm list` you can see your workspaces (defined by the workspaces property in the root package.json):
> 
> ```shell
> npm list 
> node-starter@ /home/projects/stackblitz-starters-vjwvke
> +-- a@ -> ./packages/a
> | `-- chalk@5.3.0
> `-- b@ -> ./packages/b
>   +-- a@ deduped -> ./packages/a
>   `-- chalk@5.3.0 deduped
> ```
> 
> I had added chalk as a dependency to both packages simultaneously by running:
> 
> ```shell
> npm i chalk -w a -w b
> ```
> 
> And as you can see by the resulting workspace it worked just fine

Yes you are right,  my question is actually about how to use npm workspaces.  Your answer has solved my doubts. Thank you for kindly helping me solve my doubts.

**Pull request merged**
