### PR TITLE
fix(publish): Allow tag check to fail with strong warning

### PR DESCRIPTION
**Pull request by pablolmiranda**
## Description
When using the `lerna publish` command the `--skip-git` option is not taking in consideration.

In this case, even when using the `--skip-git` option, before the `npm publish`, lerna is trying to get and create the tag for the publishing.

Passing the `s=--skip-git` option should avoid the git interaction on this flow.

## Motivation and Context
Related to https://github.com/lerna/lerna/issues/16

## How Has This Been Tested?
 - Current state:
`lerna publish --skip-git` will check and create the tags before publishing the packages
- This PR:
`lerna publish --skip-git` will skip the tags check and creation and publish the modules to NPM

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** document.
- [-] I have added tests to cover my changes.
- [-] All new and existing tests passed.

Some tests are not passing, but looks like it is not related to my changes.

I need some help writing a test to cover this flow.

### CODE REVIEW

**Comment by evocateur** [comment]
So, `--skip-git` is a terribly-named flag. It doesn't actually skip _all_ git operations, just making commits and pushing to the remote. git tags are still necessary to determine the version.

Because `lerna publish` is actually the conflation of `npm version` and `npm publish` (not my choice), we're kinda stuck with this. What are you trying to accomplish, specifically?

**Comment by evocateur** [comment]
If you don't have any git tags reachable from that branch, that's a deeper problem. Presumably lerna has successfully published on `master` before?

(I don't recommend `lerna publish` on a branch, for this and many other reasons)

**Comment by pablolmiranda** [comment]
I had a successful publish from master.

**Comment by pablolmiranda** [comment]
@evocateur, you suggestion worked. Take a look and let me know if that was what you have in mind.

**Pull request merged**
