### PR TITLE
[Internal] Normalize trailing slash on failing test by using path.resolve

### PR DESCRIPTION
**Pull request by darrylhodgins**

### CODE REVIEW

**Comment by darrylhodgins** [comment]
Thought that might help, but there's some kind of permissions thing going on with Appveyor.  Hmm…

**Comment by lukebatchelor** [comment]
I was getting the same thing but only on 1 of 5 builds. As a workaround, I amended the previous commit and force pushed a couple of times and it worked eventually.

**Comment by thejameskyle** [comment]
There do seem to be valid errors in the AppVeyor results https://ci.appveyor.com/project/lerna/lerna/build/1.0.201/job/f6ngx7r1msgcotve#L1069

**Comment by thejameskyle** [comment]
UGHH WINDOWS YOU FIREY PIECE OF SHIT!

I'm sorry dude... I don't know what is happening in AppVeyor.

**Comment by evocateur** [comment]
I'm pretty sure we already have most, if not all of the changes from this PR.

**Pull request closed without merging**
