### PR TITLE
[FAQ] Use lerna without global installation

### PR DESCRIPTION
**Pull request by XanderLuciano**
## Motivation and Context

I like to avoid adding global npm packages if I can.   
I could only find this issue on the topic: https://github.com/lerna/lerna/issues/138

The solution provided is clean, simple, and effective. Since we already have a tip for CI setup, I thought it made sense to also include a small snippet about local usage. 

## Types of changes

I have adapted the solution provided in that issue thread and added it to the FAQ.

This simple (1 line change) change to package.json is all it takes to accomplish this.

## How Has This Been Tested?
I used the "preview" tab on Github.

## Checklist:

- [ ] My code follows the code style of this project. **N/A**
- [x] My change ~~requires~~ **is** a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes. **N/A**
- [ ] All new and existing tests passed. **N/A**

### CODE REVIEW

**Comment by tivac** [comment]
I prefer using `npx` over scripts these days. `npx lerna` works great.

**Comment by XanderLuciano** [comment]
@tivac That... is infinitely easier. I wasn't even aware of `npx`.  I'll have to update this later.

**Comment by giladgray** [comment]
also if you're using yarn then it's simply `yarn lerna ...`

**Comment by jdxcode** [comment]
`echo 'export PATH="./node_modules/.bin:$PATH"' >> ~/.bashrc`

**Comment by giladgray** [comment]
@jdxcode oof that just puts _one_ of your node_modules directories in your path. what about the dozens of other repos you have checked out?

**Comment by jdxcode** [comment]
it puts the node module of your _current_ directory in your PATH

**Comment by giladgray** [comment]
ok interesting, it is relative at all times

**Comment by evocateur** [comment]
Closed due to lack of response.

**Pull request closed without merging**
