### PR TITLE
docs: add maintenance note to README

### PR DESCRIPTION
**Pull request by inca**
This PR adds a note about the state of this amazing project, as per [discussion](https://github.com/lerna/lerna/issues/2703#issuecomment-1071111156).

## Motivation and Context

This project has been struggling to keep up with the growing number of issues due to the lack of active maintainers, the size of the codebase and the dependence on package managers.  Whilst technically Lerna commands still work, the stability and the overall user experience of using Lerna alongside up-to-date versions of package managers degrades with every release of npm, yarn and/or pnpm — as is indicated by a growing number of issues.

The large user base coming here risks adopting a workflow and toolset which is not future proof.

This note merely states the facts from https://github.com/lerna/lerna/issues/2703 and aims at assisting new and existing developers at making an informed decision about investing their effort into Lerna. Please feel free to change it as you see fit.

Note: I didn't include a list of alternatives to migrate, as I am unaware of an unopinionated/curated list of monorepo management tools. The only [resource](https://monorepo.tools/) I had in mind seems a little biased to me.

### CODE REVIEW

**Comment by escapedcat** [comment]
@evocateur would you be so kind having a look if this warning can help others?

**Comment by laurent22** [comment]
I don't think "Lerna Lite" should be mentioned in the warning. It's not an official replacement and hasn't been around long enough to justify endorsing it. Just the warning and link to the issue, so that people can make their own mind, seems enough.

**Comment by inca** [comment]
Thank you, amended.

**Comment by metasean** [comment]
re: a list of possible alternatives

It might be worthwhile pointing folks to https://github.com/korfuri/awesome-monorepo

**Comment by inca** [comment]
@metasean Thanks! This one definitely looks more neutral, so I don't mind including it.

cc @escapedcat @laurent22 WDYT?

**Comment by laurent22** [comment]
I agree, it seem to be a good resource to setup a monorepo.

**Comment by escapedcat** [comment]
I think it's nice but maybe better to get the current message in first.
Like this it might be faster and easier to get it merged by the team.

**Comment by inca** [comment]
Sorry for the chasing — can we please have this merged any time soon?

cc @evocateur not sure if you are still around; I'll try cc-ing the rest of the [Lerna people](https://github.com/orgs/lerna/people) if not. Not sure who else to cc, any suggestions are welcome.

**Comment by escapedcat** [comment]
Thanks @MikeActually ! ❤️

**Comment by juristr** [comment]
> Note: I didn't include a list of alternatives to migrate, as I am unaware of an unopinionated/curated list of monorepo management tools. The only [resource](https://monorepo.tools/) I had in mind seems a little biased to me.

@inca Hey, I saw the update on the README and actually came here to propose linking to monorepo.tools, but then noticed you mentioned it seems biased to you. Granted, we (from Nx) created the page 🙂. But we on purpose kept it [open source](https://github.com/nrwl/monorepo.tools) and actively mentioned we are happy to accept PRs or discuss adjustments. We actually got amazing feedback from folks like Lage, Bazel and Gradle 🙂.

Did you have anything specific in mind that made it look biased to you? Happy to discuss 🙂

**Comment by inca** [comment]
Haha sorry, didn't mean to offend you folks, you did an amazing job — both with Nx and monorepo.tools.

Still, even if 100% objective, my brain's heuristics classify this resource as marketing based on 1) the page was created by NX and 2) this:

Screenshot 2022-04-28 at 09 27 33

So it didn't feel right to include it into the maintenance note, because it's definitely not intended to be an acquisition channel for another product. The intention was to just state the facts and let the users decide what to do next, without nudging them in a particular direction. If we need to include some pointers, then — as a user — I'd much rather go with https://github.com/korfuri/awesome-monorepo as per the suggestion above, simply because it has a "community feel" to it.

Idk how to explain it better, but hopefully you get the point. Apologies again if my original comment has upset you — definitely not intended if so.

**Comment by juristr** [comment]
@inca Oh not offended at all 😄

This was more to reach out to see whether we can add some more info around Lerna on the page or whether we got something wrong. We reached out to all the tool creators on the page and actually got quite some valuable feedback and even PRs.

> Still, even if 100% objective, my brain's heuristics classify this resource as marketing based on 1) the page was created by NX and 2) this:

I get what you mean 🙂. We created it because we have 5+ years of experience in working with monorepos in large organizations. So that's our way to help contribute to solving some of the confusion & misconception in the space. 
And for 2): yep, most (not all) boxes are checked for Nx, so they are for Bazel and many of the other listed tools will follow and we will update the page accordingly (or folks can submit PRs). It is basically showing the full feature set that - granted - we at Nx have seen to be vital when you have large monorepos. That's why we added those features in Nx in the first place and as a consequence, most of them are obviously checked for Nx 😅.

Thanks for replying 🙂

**Pull request merged**
