### PR TITLE
[Feature] Support relative dependencies within the repo

### PR DESCRIPTION
**Pull request by gigabo**
We use [relative dependencies in private packages](https://github.com/redfin/react-server/blob/master/packages/react-server-test-pages/package.json#L21-L23) as a crude workaround for #11.

This generates warnings during bootstrap, and prevents us from receiving the full benefit of #199.

This patch causes bootstrap to treat relative dependencies as satisfactory.

### CODE REVIEW

**Comment by thejameskyle** [comment]
How do the [relative dependencies](https://github.com/redfin/react-server/blob/master/packages/react-server-test-pages/package.json#L21-L23) work when publishing that module?

**Comment by gigabo** [comment]
We only do it on private modules, so they don't get published.

**Comment by gigabo** [comment]
Should probably actually be an _error_ to do it on a public repo...

**Comment by patrickheeney** [comment]
I tried to add support for this in #10 but it was closed (also is outdated now). This may also work for my use case but it would need to support the other ways to declare relative dependencies:

```
"dependencies": {
    "some-local-dependency": "file:../some-local-dependency"
},
```

It may be worthwhile to use the same logic npm uses internally to determine if this is a local dependency or not.

**Comment by gigabo** [comment]
> the other ways to declare relative dependencies

Oh yeah, good point.  Thanks for the link to `npm-package-arg`.

I've actually realized since opening this that local dependencies are a little trickier than I originally thought.  Specifically, running `npm install ../some-local-dependency` isn't actually correct if `some-local-dependency` _itself_ has non-local dependencies on packages that live in the repo.

For example with deps that look like:

```
package-a => "../package-b"
package-b => "package-c@^1.0.0"
```

If `package-c` lives in the repo it should be linked for `package-b`.

Not sure what to do about that case.

**Comment by patrickheeney** [comment]
I think the first step is something like you have done, which is to make sure the local file based packages can be bootstrapped at all. I haven't looked into it since #10, but back then private / local packages were excluded from `lerna`. 

Then likely the bootstrap process needs to be modified to detect that `package-c` needs to be linked from `package-b`. That is likely related to my other issue #11 since I currently solved it by symlinking all package dependencies as a last step after `npm install` (see Global Cache / Symlink approach in that issue).

**Comment by gigabo** [comment]
> back then private / local packages were excluded from lerna.

They're `npm install`ed now.  It actually works fine on the surface.  It's just with transitive dependencies that it starts to fall apart.

>  the bootstrap process needs to be modified to detect that package-c needs to be linked from package-b. 

Right, but _when_ is it linked?  It can't happen _before_ `npm install`, because the target in `node_modules` gets fresh copies of dependencies.  It can't happen _after_ `npm install`, because the dependency may be _used_ during install (in a `prepublish` script).  So, it would need to be linked _during_ install.  I don't know that `npm` provides the hooks we would need to do this without reimplementing `npm install` at a high level.

**Comment by patrickheeney** [comment]
> Right, but when is it linked?

At the root level this is how I am doing it at the moment:

- Get a list of all project packages
- Symlink them in node_modules project node_modules so they can be resolved
- Diff local packages against package.json and pass non-local ones to npm install
- Do the same for each package

If each package is installed separately then all the other non-local dependencies, then in theory by the time the dependency packages are installed you already have the right local one.

I am also using `pnpm` because of global cache, faster, and easier to pass it CLI arguments. I don't think this easily supports multiple versions of the same local dependency (but could maybe?). I haven't had an issue with scripts but I imagine there is some scenario where this might not work?

**Comment by evocateur** [comment]
@gigabo Can we close this PR now?

**Comment by gigabo** [comment]
Yes!

**Pull request closed without merging**
