### PR TITLE
chore(deps): bump pacote & npm-packlist to latest versions

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
I was looking into #3226 and noticed an install warning about a deprecated version of npm-packlist being used; this turned out to be caused by an outdated version of pacote, so upgrading that works.

~That said though, lerna does still directly depend on npm-packlist @ 2.1.4, instead of 5.x.y, so there may be issues there.~

Edit: Have added a commit to upgrade `npm-packlist` to 5.1.1, same as pacote.

## Motivation and Context

Fixes an install warning about a deprecated dependency.

## How Has This Been Tested?

Have relied on CI and the changelogs of the packages involved to look for breaking changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (change that has absolutely no effect on users)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
I've also added a commit to upgrade npm-packlist, and the unit tests seem to succeed; I'll let the e2e tests run on actions instead.

**Comment by ThisIsMissEm** [comment]
Ah, sure thing! I wasn't sure what the standard was these days (it's been a while since I contributed).

**Comment by JamesHenry** [comment]
Yes I’m afraid it’s this https://github.com/lerna/lerna/issues/3225

Please could you commit the result of npm run format:write

**Comment by JamesHenry** [comment]
@ThisIsMissEm Ok so apparently this giant lock file diff thing is catching 😅 

I have just recreated your change here https://github.com/lerna/lerna/pull/3238/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519 and it's 1/10th the diff:

image

**Comment by JamesHenry** [comment]
What happens if you just run npm install against the main branch? Does it generate a diff even then?

**Comment by JamesHenry** [comment]
@ThisIsMissEm hope you feel better soon! Would you like me to press ahead with my replica PR in the meantime, or wait until you have chance to investigate? I don't mind which

**Comment by ThisIsMissEm** [comment]
I'll try to follow up this week

Emelia

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
Thanks again @ThisIsMissEm!

**Pull request merged**
