### PR TITLE
fix(run): always set env LERNA_PACKAGE_NAME environment variable

### PR DESCRIPTION
**Pull request by raphaelboukara**
Set variable environment `LERNA_PACKAGE_NAME` for `lerna run ...`.

## Description
When running `lerna exec ...`, lerna will run with variable environment `LERNA_PACKAGE_NAME`. This variable is not settled with `lerna run ...`.

## Motivation and Context
This change is required since it seems legit to get same variable environments for both `lerna exec` and `lerna run`.
This one doesn't fix an open issue, should I open one?

## How Has This Been Tested?
To test my changes, I link lerna locally via `npm link`, I run `lerna run myscript` to log variable environment `LERNA_PACKAGE_NAME`.
I used using node v16.13.1 (npm v8.1.4) during my test.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project. **It doesn't seems since lint failed locally but I didn't change nothing.**
- [ ] My change requires a change to the documentation. **I am not sur about this one.**
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes. **Can you drive me where to add test?**
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by raphaelboukara** [comment]
Hi, can you help me to move forward with this one?

**Comment by ghost91-** [comment]
It seems like a straight forward improvement to me. The lack of feedback is most likely just due to the fact that lerna is largely unmaintained at this point (see https://github.com/lerna/lerna/pull/3092)

**Review by icrotz — DISMISSED** [review]

**Comment by ghiscoding** [comment]
Hey everyone, this was implemented in Lerna-Lite release [1.2.0](https://github.com/ghiscoding/lerna-lite/releases/tag/v1.2.0) if that interests you. Cheers and happy coding

**Review by JamesHenry — CHANGES_REQUESTED** [review]
Thanks a lot for this @raphaelboukara!

We've merged support for this when `useNx: true` and this would allow for it to always be set for all `lerna run` implementations.

Please could you update the branch so that it passes our latest CI? I imagine it is just failing the formatting check.

**Comment by raphaelboukara** [comment]
@JamesHenry the CI seems stuck, I have to do something else?

**Comment by JamesHenry** [comment]
@raphaelboukara I had to approve your first run, you should be good to iterate now, thanks!

**Comment by JamesHenry** [comment]
@raphaelboukara just following up on this

**Comment by JamesHenry** [comment]
@raphaelboukara so as to not leave this one unaddressed any longer, I went ahead and applied the change and added the relevant tests in #3359 

Thanks again for contributing to lerna and its community! 🙏

**Pull request closed without merging**
